// src/Places.tsx
import React, { useEffect, useState } from "react";
import { Place } from "./interfaces/place";
import { database } from "./Firebase";
import { Card } from "./components/card";

export const Places = (): JSX.Element => {
  const [places, setPlaces] = useState<Place[]>([]);
  useEffect(() => {
    database
      .collection("places")
      .limit(10)
      .get()
      .then(result => {
        const fetchedPlaces: Place[] = [];
        result.docs.forEach(doc => {
          fetchedPlaces.push({ ...doc.data(), id: doc.id } as Place);
        });
        setPlaces(fetchedPlaces);
      });
  }, []);

  const placeCards = places.map(place => (
    <Card
      title={place.name}
      link={`https://www.google.co.uk/maps/search/?api=1&query=${place.name}, ${place.address}`}
      linkText={place.address}
      content={place.description}
      key={place.id}
    />
  ));

  return places.length ? (
    <div className="card-container">{placeCards}</div>
  ) : (
    <h2>Loading...</h2>
  );
};

// src/views/Places.vue
<template>
  <div>
    <Card
      v-for="place in places"
      :key="place.id"
      :title="place.name"
      :link="toMapLink(place.name, place.address)"
      :linkText="place.address"
      :content="place.description"
    />
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
import Card from '@/components/Card.vue'
import { database } from '@/firebase'
import { Place } from '@/types/place'

@Component({
  components: {
    Card
  }
})
export default class Places extends Vue {
  get places(): Place[] {
    return this.$store.state.places
  }

  set places(places: Place[]) {
    this.$store.commit('setPlaces', places)
  }

  private async fetchPlaces() {
    try {
      const result = await database
        .collection('places')
        .limit(10)
        .get()

      const fetchedPlaces: Place[] = []
      result.docs.forEach(doc => {
        fetchedPlaces.push({ ...doc.data(), id: doc.id } as Place)
      })
      this.places = fetchedPlaces
    } catch (error) {
      alert(error.message)
    }
  }

  private toMapLink(name: string, address: string) {
    return `https://www.google.co.uk/maps/search/?api=1&query=${name}, ${address}`
  }

  mounted() {
    if (!this.places.length) {
      this.fetchPlaces()
    }
  }
}
</script>
